layout_spectrum: 0.7748253226745874
typography_spectrum: 0.061528272926807404
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.480755785247311
  lightness: 0.8205762659199536
  saturation: 0.04360396903939545
  rhythmicContrast: 0.2320723570883274
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/15421f56-0f5e-405c-865b-bfdcf30c18b5.png
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Joyfulvibrantlife
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/46e0e1a2-7a47-4eff-b859-e0e7ca57a0b1.png
title: Joyful Vibrant Life
description: Thrive in a Stressful World
purpose: []
