name: Joyfulvibrantlife
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5012
navigation:
  - name: home
    id: c86e6cdd-587c-45e0-8bad-8e84fd08686d
    type: content
title: Joyful Vibrant Life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefe00'
    - '#02fa00'
    - '#fc0000'
    - '#0000fa'
    - '#ff8400'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
