layout_spectrum: 0.5512940071057528
typography_spectrum: 0.7720584648195654
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.1942348638549447
  lightness: 0.16354500874876976
  saturation: 0.7463716114871204
  rhythmicContrast: 0.06739755300804973
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/15421f56-0f5e-405c-865b-bfdcf30c18b5.png
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Joyful Vibrant Life
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/46e0e1a2-7a47-4eff-b859-e0e7ca57a0b1.png
title: Fresh Perspectives
description: To Thrive in a Stressful World
purpose: []
