name: Joyfulvibrantlife
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5012
navigation:
  - name: home
    id: c86e6cdd-587c-45e0-8bad-8e84fd08686d
    type: content
title: Joyful Vibrant Life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dc0773'
    - '#ffa640'
    - '#ee4446'
    - '#fff9ff'
    - '#d66da9'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
