name: Joyful Vibrant Life
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/46e0e1a2-7a47-4eff-b859-e0e7ca57a0b1.png
layout_spectrum: 0.44146779319271445
typography_spectrum: 0.9173694646451622
author:
  name: Sandy Freschi
  email: coachingwithsandy@gmail.com
  url: 'http://www.coachingwithsandy.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/53779a38-46b0-4963-a689-fae5f502c833.jpg
title: Fresh Perspectives
description: To Thrive in a Stressful World
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: sandyfreschi
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f35e36'
    - '#c10303'
    - '#fed008'
    - '#ffa340'
    - '#ffeef6'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.9375
  rhythmicContrast: 0
purpose: []
