layout_spectrum: 0.753062620991841
typography_spectrum: 0.12941351742483675
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.48249868699349463
  lightness: 0.47758888453245163
  saturation: 0.9873940811958164
  rhythmicContrast: 0.6104771438986063
opengraph: {}
analytics:
  facebook: '599930050163860'
  google: UA-82992219-1
  twitter: sandyfreschi
author:
  name: Sandy Freschi
  url: 'http://coachingwithsandy.com'
  email: coachingwithsandy@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/53779a38-46b0-4963-a689-fae5f502c833.jpg
name: Joyful Vibrant Life
cta: {}
navigation:
  - name: About
    url: 'http://coachingwithsandy.com/about-me/'
    type: external
  - name: Services
    url: 'http://coachingwithsandy.com/services/'
    type: external
  - name: Career Success
    url: 'https://bg5businessinstitute.com/?consultant=18'
    type: external
  - name: Deep Healing
    url: >-
      http://www.quantumtouch.com/index.php?option=com_training&view=training&Itemid=179&partner_id=1000009457
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/46e0e1a2-7a47-4eff-b859-e0e7ca57a0b1.png
title: Fresh Perspectives
description: to thrive in a stressful world
purpose: []
