typography_spectrum: 0.5012
color:
  brandColors:
    - '#dc0773'
    - '#ffa640'
    - '#ee4446'
    - '#fff9ff'
    - '#d66da9'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/15421f56-0f5e-405c-865b-bfdcf30c18b5.png
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Joyfulvibrantlife
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/46e0e1a2-7a47-4eff-b859-e0e7ca57a0b1.png
title: Joyful Vibrant Life
description: Thrive in a Stressful World
purpose: []
