name: Joyfulvibrantlife
favicon: null
layout_spectrum: 0.6116591633763164
typography_spectrum: 0.24574654083698988
title: Joyful Vibrant Life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefd0c'
    - '#fe3200'
    - '#350e00'
    - '#fe8500'
    - '#12b439'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 1
  rhythmicContrast: 0
purpose: []
