name: Joyfulvibrantlife
favicon: null
layout_spectrum: 0.6116591633763164
typography_spectrum: 0.24574654083698988
title: Joyful Vibrant Life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ee8903'
    - '#fffeff'
    - '#55874e'
    - '#a31000'
  brandStrength: 0.5625
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
