layout_spectrum: 0.753062620991841
typography_spectrum: 0.27604083460755646
color:
  brandColors:
    - '#FFC300'
    - '#900C3E'
    - '#FF5733'
    - '#571845'
    - '#A33962'
  brandStrength: 0.10379403433762491
  lightness: 0.6070757491979748
  saturation: 0.5172945039812475
  rhythmicContrast: 0.873398823197931
opengraph: {}
analytics:
  facebook: '599930050163860'
  google: UA-82992219-1
  twitter: sandyfreschi
author:
  name: Sandy Freschi
  url: 'http://coachingwithsandy.com'
  email: coachingwithsandy@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/53779a38-46b0-4963-a689-fae5f502c833.jpg
name: Joyful Vibrant Life
cta: {}
navigation:
  - name: About
    url: 'http://coachingwithsandy.com/about-me/'
    type: external
  - name: Services
    url: 'http://coachingwithsandy.com/services/'
    type: external
  - name: Career Success
    url: 'https://bg5businessinstitute.com/?consultant=18'
    type: external
  - name: Deep Healing
    url: >-
      http://www.quantumtouch.com/index.php?option=com_training&view=training&Itemid=179&partner_id=1000009457
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/46e0e1a2-7a47-4eff-b859-e0e7ca57a0b1.png
title: Fresh Perspectives
description: for thriving in a stressful world
purpose: []
