layout_spectrum: 0.04469239991158247
typography_spectrum: 0.6486842269077897
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.7422727830708027
  lightness: 0.19467090303078294
  saturation: 0.85861128102988
  rhythmicContrast: 0.5538928697351366
name: Joyful Vibrant Life
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/46e0e1a2-7a47-4eff-b859-e0e7ca57a0b1.png
author:
  name: Sandy Freschi
  email: coachingwithsandy@gmail.com
  url: 'http://www.coachingwithsandy.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/53779a38-46b0-4963-a689-fae5f502c833.jpg
title: Fresh Perspectives
description: To Thrive in a Stressful World
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: sandyfreschi
opengraph:
  image: null
  type: null
  appId: null
purpose: []
