typography_spectrum: 0.0941796493716538
color:
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  brandStrength: 0.2234190523158759
  lightness: 0.9987920022103935
  saturation: 0.05217057024128735
  rhythmicContrast: 0.89627203065902
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/15421f56-0f5e-405c-865b-bfdcf30c18b5.png
  type: null
  appId: null
layout_spectrum: 0.754800142487511
analytics:
  google: null
  facebook: null
  twitter: null
name: Joyful Vibrant Life
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/46e0e1a2-7a47-4eff-b859-e0e7ca57a0b1.png
title: Fresh Perspectives
description: Thrive in a Stressful World
purpose: []
